steps:
  compile-asar:
    image: node:20
    commands:
      - |
        COMMIT_MSG="$(git log -1 --pretty=%B)"
        echo "Latest commit message: $COMMIT_MSG"
        if ! echo "$COMMIT_MSG" | grep -qE '^\[v'; then
          echo "Commit message does not start with [v — skipping build."
          exit 78
        fi
      - npm install -g asar
      - asar p . app.asar
    
    when:
      event:
        - push

  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - app.asar
      api_key:
        from_secret: ACCESS_TOKEN
    when:
      event:
        - push