when:
  event:
    - tag  

steps:
  compile-asar:
    image: node:20
    commands:
      - npm install -g asar
      - asar p . app.asar

  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - app.asar
      api_key:
        from_secret: ACCESS_TOKEN
    when:
      event:
        - tag
