when: 
  event:
    - tag

steps:
  - name: compile asar
    image: node:20
    commands:
      - npm install -g asar
      - asar p . app.asar

  - name: get app files from remote
    image: node:20
    commands:
      - cd ../
      - mkdir -p temp
      - curl -o temp/macos.zip https://fileserver.crjakob.com/PolyModLoader/macos.zip
      - curl -o temp/linux.zip https://fileserver.crjakob.com/PolyModLoader/linux.zip
      - curl -o temp/windows.zip https://fileserver.crjakob.com/PolyModLoader/windows.zip

  - name: copy asar to app files
    image: node:20
    commands:
      - cd ../
      - apt-get update && apt-get install -y zip
      - mkdir -p temp/resources
      - cp PolyModLoader/app.asar temp/resources/app.asar
      - cd temp
      - zip -g windows.zip resources/app.asar
      - zip -g linux.zip resources/app.asar
      - cd ../
      - rm -rf temp/resources
      - mkdir -p temp/PolyTrack.app/Contents/resources
      - cp PolyModLoader/app.asar temp/PolyTrack.app/Contents/resources/app.asar
      - cd temp/
      - zip -r macos.zip PolyTrack.app/Contents/resources/app.asar


  - name: create release
    image: woodpeckerci/plugin-release
    settings:
      files:
        - ../temp/PolyTrack.app/Contents/resources/app.asar
        - ../temp/macos.zip
        - ../temp/linux.zip
        - ../temp/windows.zip
      api_key:
        from_secret: ACCESS_TOKEN